use curve25519_dalek::edwards::CompressedEdwardsY;
use ed25519_dalek::{
    Signer, SigningKey, VerifyingKey,
    hazmat::{ExpandedSecretKey, raw_sign},
};
use mcrs_protocol::{PUB_KEY_SIZE, node_hash};
use sha2::{Digest, Sha512};

pub const NODE_HASH_SIZE: usize = 4;
pub const REMOTE_CLI_PASSWORD: &str = "meshcore";

#[derive(Clone, Copy, PartialEq, Eq)]
pub enum PrivateKey {
    Seed([u8; 32]),
    Expanded([u8; 64]),
}

impl core::fmt::Debug for PrivateKey {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str("PrivateKey(<redacted>)")
    }
}

impl PrivateKey {
    pub fn from_hex(input: &str) -> Option<Self> {
        fn decode<const N: usize>(input: &str) -> Option<[u8; N]> {
            if input.len() != N * 2 {
                return None;
            }
            let mut bytes = [0; N];
            for (byte, pair) in bytes.iter_mut().zip(input.as_bytes().chunks_exact(2)) {
                let high = (pair[0] as char).to_digit(16)?;
                let low = (pair[1] as char).to_digit(16)?;
                *byte = (high * 16 + low) as u8;
            }
            Some(bytes)
        }
        match input.len() {
            64 => Some(Self::Seed(decode(input)?)),
            128 => {
                let bytes: [u8; 64] = decode(input)?;
                // MeshCore exports the clamped scalar followed by the nonce prefix.
                if bytes[0] & 7 != 0 || bytes[31] & 0xc0 != 0x40 {
                    return None;
                }
                Some(Self::Expanded(bytes))
            }
            _ => None,
        }
    }

    pub fn as_bytes(&self) -> &[u8] {
        match self {
            Self::Seed(bytes) => bytes,
            Self::Expanded(bytes) => bytes,
        }
    }

    pub fn config_key(&self) -> &'static str {
        match self {
            Self::Seed(_) => "identity.seed",
            Self::Expanded(_) => "identity.expanded",
        }
    }

    fn expanded_bytes(&self) -> [u8; 64] {
        match self {
            Self::Seed(seed) => Sha512::digest(seed).into(),
            Self::Expanded(bytes) => *bytes,
        }
    }
}

#[derive(Clone, Copy)]
pub struct Identity {
    public_key: [u8; PUB_KEY_SIZE],
    node_hash: [u8; NODE_HASH_SIZE],
    x25519_scalar: [u8; 32],
    private_key: PrivateKey,
}

impl Identity {
    pub fn from_private_key(private_key: PrivateKey) -> Self {
        let expanded = private_key.expanded_bytes();
        let public_key = VerifyingKey::from(&ExpandedSecretKey::from_bytes(&expanded)).to_bytes();
        let node_hash = node_hash::<NODE_HASH_SIZE>(&public_key);
        let mut x25519_scalar = [0; 32];
        x25519_scalar.copy_from_slice(&expanded[..32]);
        Self {
            public_key,
            node_hash,
            x25519_scalar,
            private_key,
        }
    }

    pub fn sign(&self, message: &[u8]) -> [u8; 64] {
        match &self.private_key {
            PrivateKey::Seed(seed) => SigningKey::from_bytes(seed).sign(message).to_bytes(),
            PrivateKey::Expanded(bytes) => {
                let secret = ExpandedSecretKey::from_bytes(bytes);
                let public = VerifyingKey::from(&secret);
                raw_sign::<Sha512>(&secret, message, &public).to_bytes()
            }
        }
    }

    pub fn public_key(&self) -> &[u8; PUB_KEY_SIZE] {
        &self.public_key
    }

    pub fn node_hash(&self) -> &[u8; NODE_HASH_SIZE] {
        &self.node_hash
    }

    pub fn shared_secret_with_ed25519_public(
        &self,
        peer_public_key: &[u8; PUB_KEY_SIZE],
    ) -> Option<[u8; 32]> {
        let peer_point = CompressedEdwardsY(*peer_public_key).decompress()?;
        let shared = peer_point.to_montgomery().mul_clamped(self.x25519_scalar).0;

        if shared == [0; 32] {
            return None;
        }

        Some(shared)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::{format, string::String};

    // Generated by MeshCore's lib/ed25519 from seed [7; 32], with peer seed [9; 32].
    pub const EXPANDED: &str = "28ad39fefd7fa3e200a9c626eef599e61a2d055c48a8288a4e7e4c4bca3928789c7d6db3506d65dbac7c052aaee4857425210c9bc54030c826e54055983452a5";
    fn hex(bytes: &[u8]) -> String {
        bytes.iter().map(|byte| format!("{byte:02x}")).collect()
    }

    #[test]
    fn expanded_key_matches_meshcore() {
        let key = PrivateKey::from_hex(EXPANDED).unwrap();
        let identity = Identity::from_private_key(key);
        assert_eq!(
            hex(identity.public_key()),
            "ea4a6c63e29c520abef5507b132ec5f9954776aebebe7b92421eea691446d22c"
        );
        let message = b"meshcore-rs expanded import";
        let signature = identity.sign(message);
        assert_eq!(
            hex(&signature),
            "a118fb4c6cc13c483236ef963301972fe7473f70e7ae7945e87cf5c8d20da9a7e664369f5c5c7382e6934d45af637ea3b80078a9299e2ca7d3447b06c5b7e807"
        );
        VerifyingKey::from_bytes(identity.public_key())
            .unwrap()
            .verify_strict(message, &ed25519_dalek::Signature::from_bytes(&signature))
            .unwrap();
        let peer = Identity::from_private_key(PrivateKey::Seed([9; 32]));
        let shared = identity
            .shared_secret_with_ed25519_public(peer.public_key())
            .unwrap();
        assert_eq!(
            hex(&shared),
            "2cb7f43f03eba482d4605e910e04c9209c90c3cf50dbf1ff3f2bd641d468bf16"
        );
        assert_eq!(
            peer.shared_secret_with_ed25519_public(identity.public_key()),
            Some(shared)
        );
    }

    #[test]
    fn seed_and_expanded_forms_have_the_same_identity() {
        let seed = Identity::from_private_key(PrivateKey::Seed([7; 32]));
        let expanded = Identity::from_private_key(PrivateKey::from_hex(EXPANDED).unwrap());
        assert_eq!(seed.public_key(), expanded.public_key());
        assert_eq!(seed.sign(b"advert"), expanded.sign(b"advert"));
        assert_eq!(
            seed.sign(b"advert"),
            SigningKey::from_bytes(&[7; 32]).sign(b"advert").to_bytes()
        );
    }

    #[test]
    fn parses_both_formats_and_rejects_bad_keys() {
        assert_eq!(
            PrivateKey::from_hex(&"07".repeat(32)),
            Some(PrivateKey::Seed([7; 32]))
        );
        assert_eq!(
            PrivateKey::from_hex(&EXPANDED.to_uppercase()),
            PrivateKey::from_hex(EXPANDED)
        );
        for input in [
            "",
            &"00".repeat(31),
            &"00".repeat(33),
            &"00".repeat(64),
            &"ff".repeat(64),
            &"zz".repeat(32),
        ] {
            assert!(PrivateKey::from_hex(input).is_none());
        }
        let mut bytes = PrivateKey::from_hex(EXPANDED).unwrap().as_bytes().to_vec();
        bytes[0] |= 1;
        assert!(PrivateKey::from_hex(&hex(&bytes)).is_none());
    }
}
